# Generated by Django 3.1.2 on 2020-10-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='media/uploads/%Y/%m/%d'),
        ),
    ]
